---
title: "Validation - Obuchowski Sample Size Table"
format:   
  html:
    self-contained: true
    toc: true
    number-depth: 3
editor: visual
execute-dir: project
execute:
  echo: false
  warning: false
---

## Compare our Sample Size to Obuchowski Table

```{r}

source("functions_moments.R")

library(purrr)
library(gt)
library(tidyverse)
library(dplyr)
library(MRMCsamplesize)

```

```{r}

# --- Generate combined Table 1 + 2 scenario grid ---
tab2_OR_scenarios <- build_OR_scenarios()
head(tab2_OR_scenarios)

```

```{r}

mrmc_ss(readers = 4, accuracy_level = 0.75, 
        delta = 0.05, ratio = 1, rangeb = 0.01, rangew = 0.005, 
        r1 = 0.47, r2 = 0.3, r3 = 0.3, rb = 0.8, 
                            design = "FC",
                            G = NULL, NR_groups = NULL,
                            alpha = 0.05, target_power = 0.80,
                            search_min = 10, search_max = 5000)

sampleSize_MRMC(endpoint = "auc",
  J = 4,
  delta = 0.05,
  rangeb = 0.01, 
  rangew = 0.005,
  theta = 0.75,
  R = 1,
  r1 = 0.47,
  r2 = 0.3,
  r3 = 0.3,
  rb = 0.8,
  K = 1,
  power = 0.8,
  alpha = 0.05,
  reader_var_estimation_method = "not normal")


```

## RJafroc

```{r}

library(RJafroc)

or_var_comps<-sampleSize_MRMC(endpoint = "auc",
  J = 4,
  delta = 0.05,
  rangeb = 0.01, 
  rangew = 0.005,
  theta = 0.75,
  R = 1,
  r1 = 0.47,
  r2 = 0.3,
  r3 = 0.3,
  rb = 0.8,
  K = 1,
  power = 0.8,
  alpha = 0.05,
  reader_var_estimation_method = "not normal")$varComponents


# SsSampleSizeKGivenJ(dataset = NULL, 
#                     KStar = 100,
#                     VarTR = or_var_comps$varTR, 
#                     Cov1 =  or_var_comps$Cov1,
#                     Cov2 = or_var_comps$Cov2,
#                     Cov3 = or_var_comps$Cov3,
#                     Var = or_var_comps$varE, 
#                     J = 4,
#                     effectSize = 0.05,
#                     method = "OR")

SsPowerGivenJKOrVarCom(J = 4,
                       K = 524,
                    KStar = 10,
                    effectSize = 0.05,
                    VarTR = or_var_comps$varTR, 
                    Cov1 =  or_var_comps$Cov1,
                    Cov2 = or_var_comps$Cov2,
                    Cov3 = or_var_comps$Cov3,
                    Var = or_var_comps$varE)


```

## References
